In [1]:
import cv2
import numpy as np
import render as r

In [6]:
image = cv2.imread('lena.png')
image2 = cv2.imread('houghTransform.png')

In [22]:
def intRound(image):
    out = np.ones(image.shape, np.uint8)
    for i in range(len(image)):
        for j in range(len(image[0])):
            for k in range(len(image[0][0])):
                if image[i][j][k] == np.Inf:
                    out[i][j][k] = 255
                else:
                    out[i][j][k] = int(image[i][j][k])
    return out
                
def normalize(image, depth, rounded=True):
    norm = (depth*(image - image.mean())/(image.std())) + 128
    if rounded:
        return intRound(norm)
    else:
        return norm

def addNoise(image, depth, intensity):    
    norm = normalize(image, depth, False)
    noisy = intRound(norm + (24*intensity/255) * norm.std() * np.random.random(norm.shape))
    return noisy

def blacken(image):
    out = np.ones(image.shape, np.uint8)
    for i in range(len(image)):
        for j in range(len(image[0])):
            for k in range(len(image[0][0])):
                if image[i][j][k] < 40:
                    out[i][j][k] = int(0)
                else:
                    out[i][j][k] = int(image[i][j][k])
    return out

In [23]:
norm = blacken(image2)

#print(hex(image2[50][50][0]))
r.dispImg(image2)
r.dispImg(norm)

In [126]:
filt = addNoise(image, 40, 12)
r.dispImg(image)
r.dispImg(filt)

In [94]:
norm = normalize(image, 50)
f = np.fft.fft2(norm)
fshift = np.fft.fftshift(f)
mag = intRound(20*np.log((np.abs(fshift)+1)))
print(mag)
#r.dispImg(mag)

[[[109 108 109]
  [106 126  97]
  [ 93 114  87]
  ...
  [ 98 112  97]
  [ 87 114  93]
  [ 97 126 106]]

 [[ 91 114  91]
  [ 83 119  97]
  [ 95 108  97]
  ...
  [ 96  85 104]
  [ 97 108  95]
  [ 97 119  83]]

 [[ 96  99  96]
  [101 100 103]
  [100 111  97]
  ...
  [100 105  80]
  [ 97 111 100]
  [103 100 101]]

 ...

 [[ 55  89  55]
  [ 91 122 103]
  [105  94 102]
  ...
  [ 55 110  88]
  [102  94 105]
  [103 122  91]]

 [[ 93  61  93]
  [ 78 112  81]
  [ 94 105 103]
  ...
  [ 81  98 103]
  [103 105  94]
  [ 81 112  78]]

 [[ 81 119  81]
  [103 119  98]
  [100  89 108]
  ...
  [ 91 124  83]
  [108  89 100]
  [ 98 119 103]]]
